const fs = require('fs');

const niches = {
  fashion: {
    vendor: 'FlexiStyle', tags_base: ['fashion', 'clothing'],
    products: [
      { title: 'Classic Fit Cotton T-Shirt', type: 'Tops', price: '29.99', compare: '39.99', tags: ['women', 'tops', 'cotton', 'best-sellers'], desc: 'Ultra-soft premium cotton t-shirt. Breathable and perfect for everyday wear.', img: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop', options: { Color: ['White', 'Black', 'Navy'], Size: ['S', 'M', 'L', 'XL'] } },
      { title: 'Slim Fit Denim Jeans', type: 'Bottoms', price: '59.99', compare: '79.99', tags: ['women', 'jeans', 'denim', 'sale'], desc: 'Premium stretch denim jeans with modern slim fit for all-day comfort.', img: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&h=800&fit=crop', options: { Color: ['Blue', 'Black'], Size: ['28', '30', '32', '34'] } },
      { title: 'Floral Print Maxi Dress', type: 'Dresses', price: '69.99', compare: '', tags: ['women', 'dresses', 'floral', 'summer', 'new-arrivals'], desc: 'Elegant floral maxi dress with flowing silhouette. Perfect for events or date nights.', img: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&h=800&fit=crop', options: { Color: ['Rose', 'Sky Blue'], Size: ['S', 'M', 'L'] } },
      { title: 'Leather Crossbody Bag', type: 'Accessories', price: '49.99', compare: '65.00', tags: ['accessories', 'bags', 'leather', 'sale'], desc: 'Genuine leather crossbody bag with adjustable strap and gold hardware.', img: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&h=800&fit=crop', options: { Color: ['Tan', 'Black', 'Burgundy'] } },
      { title: 'Oversized Knit Sweater', type: 'Tops', price: '54.99', compare: '', tags: ['women', 'tops', 'knitwear', 'winter'], desc: 'Cozy oversized chunky cable-knit sweater. Warm, soft, and endlessly stylish.', img: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&h=800&fit=crop', options: { Color: ['Cream', 'Grey', 'Olive'], Size: ['S/M', 'L/XL'] } },
      { title: 'Tailored Chino Pants', type: 'Bottoms', price: '44.99', compare: '55.00', tags: ['men', 'pants', 'chinos', 'sale'], desc: 'Sharp tailored chinos with modern fit. Office to weekend versatility.', img: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&h=800&fit=crop', options: { Color: ['Khaki', 'Navy', 'Charcoal'], Size: ['30', '32', '34', '36'] } },
      { title: 'Oxford Button-Down Shirt', type: 'Tops', price: '39.99', compare: '', tags: ['men', 'shirts', 'oxford', 'best-sellers'], desc: 'Timeless oxford button-down in crisp cotton. Every man needs this.', img: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&h=800&fit=crop', options: { Color: ['White', 'Light Blue', 'Pink'], Size: ['S', 'M', 'L', 'XL'] } },
      { title: 'Minimalist Leather Watch', type: 'Accessories', price: '89.99', compare: '120.00', tags: ['accessories', 'watches', 'leather', 'sale'], desc: 'Sleek minimalist watch with leather strap and stainless steel case.', img: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&h=800&fit=crop', options: { Color: ['Brown/Gold', 'Black/Silver'] } },
      { title: 'Silk Scarf Collection', type: 'Accessories', price: '34.99', compare: '', tags: ['accessories', 'scarves', 'silk'], desc: 'Luxurious pure silk scarf with hand-rolled edges. Instant elegance.', img: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&h=800&fit=crop', options: { Color: ['Floral', 'Geometric', 'Abstract'] } },
      { title: 'High-Rise Wide Leg Trousers', type: 'Bottoms', price: '64.99', compare: '80.00', tags: ['women', 'pants', 'wide-leg', 'sale', 'new-arrivals'], desc: 'Sophisticated high-rise wide leg trousers with flattering drape.', img: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&h=800&fit=crop', options: { Color: ['Black', 'Camel'], Size: ['S', 'M', 'L', 'XL'] } },
      { title: 'Linen Blend Blazer', type: 'Outerwear', price: '89.99', compare: '', tags: ['women', 'outerwear', 'blazer', 'linen', 'new-arrivals'], desc: 'Relaxed linen blend blazer for effortless layering. Structured yet breathable.', img: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=800&h=800&fit=crop', options: { Color: ['Sand', 'White', 'Black'], Size: ['S', 'M', 'L'] } },
      { title: 'Graphic Print Hoodie', type: 'Tops', price: '44.99', compare: '52.00', tags: ['men', 'tops', 'hoodie', 'streetwear', 'sale'], desc: 'Premium heavyweight hoodie with original graphic print. Streetwear essential.', img: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&h=800&fit=crop', options: { Color: ['Black', 'Grey', 'White'], Size: ['S', 'M', 'L', 'XL', 'XXL'] } },
      { title: 'Pleated Midi Skirt', type: 'Bottoms', price: '49.99', compare: '', tags: ['women', 'skirts', 'midi', 'elegant'], desc: 'Flowing pleated midi skirt in satin finish. Moves beautifully with every step.', img: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&h=800&fit=crop', options: { Color: ['Champagne', 'Black', 'Emerald'], Size: ['S', 'M', 'L'] } },
      { title: 'Men\'s Slim Fit Suit', type: 'Suits', price: '199.99', compare: '260.00', tags: ['men', 'suits', 'formal', 'best-sellers', 'sale'], desc: 'Modern slim fit two-piece suit in premium wool blend. Tailored to impress.', img: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&h=800&fit=crop', options: { Color: ['Navy', 'Charcoal', 'Black'], Size: ['38R', '40R', '42R', '44R'] } },
      { title: 'Cashmere V-Neck Sweater', type: 'Tops', price: '79.99', compare: '', tags: ['men', 'tops', 'cashmere', 'winter', 'best-sellers'], desc: 'Pure cashmere v-neck sweater. Incredibly soft and warm for cold weather.', img: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&h=800&fit=crop', options: { Color: ['Camel', 'Navy', 'Burgundy'], Size: ['S', 'M', 'L', 'XL'] } },
      { title: 'Crop Top Ribbed Knit', type: 'Tops', price: '24.99', compare: '', tags: ['women', 'tops', 'crop-top', 'casual', 'new-arrivals'], desc: 'Fitted ribbed knit crop top. Layer it or wear it solo for a modern look.', img: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop', options: { Color: ['White', 'Black', 'Mocha', 'Sage'], Size: ['XS', 'S', 'M', 'L'] } },
      { title: 'Cargo Jogger Pants', type: 'Bottoms', price: '42.99', compare: '50.00', tags: ['men', 'pants', 'joggers', 'streetwear', 'casual', 'sale'], desc: 'Relaxed cargo joggers with side pockets and elastic cuffs. Comfort meets utility.', img: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&h=800&fit=crop', options: { Color: ['Olive', 'Black', 'Khaki'], Size: ['S', 'M', 'L', 'XL'] } },
      { title: 'Satin Wrap Dress', type: 'Dresses', price: '74.99', compare: '', tags: ['women', 'dresses', 'satin', 'evening', 'new-arrivals'], desc: 'Luxurious satin wrap dress with a flattering tie waist. From dinner to dancing.', img: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&h=800&fit=crop', options: { Color: ['Wine', 'Black', 'Emerald'], Size: ['S', 'M', 'L'] } },
      { title: 'Denim Trucker Jacket', type: 'Outerwear', price: '64.99', compare: '78.00', tags: ['unisex', 'outerwear', 'denim', 'jacket', 'best-sellers', 'sale'], desc: 'Classic denim trucker jacket with vintage wash. Timeless layering piece.', img: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=800&h=800&fit=crop', options: { Color: ['Light Wash', 'Dark Wash', 'Black'], Size: ['S', 'M', 'L', 'XL'] } },
      { title: 'Leather Belt', type: 'Accessories', price: '29.99', compare: '', tags: ['accessories', 'belts', 'leather', 'men'], desc: 'Genuine leather belt with brushed nickel buckle. The finishing touch.', img: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop', options: { Color: ['Brown', 'Black'], Size: ['32', '34', '36', '38'] } },
    ]
  },

  baby: {
    vendor: 'FlexiBaby', tags_base: ['baby', 'kids'],
    products: [
      { title: 'Organic Cotton Onesie 3-Pack', type: 'Clothing', price: '24.99', compare: '32.00', tags: ['clothing', 'onesies', 'organic', 'newborn', 'best-sellers', 'sale'], desc: 'Ultra-soft 100% organic cotton onesies. Gentle on delicate skin, easy snap closures.', img: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800&h=800&fit=crop', options: { Color: ['White/Grey/Pink', 'White/Grey/Blue'], Size: ['0-3M', '3-6M', '6-12M'] } },
      { title: 'Bamboo Muslin Swaddle Blankets', type: 'Bedding', price: '29.99', compare: '', tags: ['bedding', 'swaddle', 'bamboo', 'newborn', 'best-sellers'], desc: 'Set of 3 breathable bamboo muslin swaddles. Soft, stretchy, and multi-purpose.', img: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&h=800&fit=crop', options: { Pattern: ['Stars', 'Animals', 'Floral'] } },
      { title: 'Silicone Teething Toy Set', type: 'Toys', price: '14.99', compare: '18.00', tags: ['toys', 'teething', 'silicone', 'bpa-free', 'sale'], desc: 'BPA-free food-grade silicone teethers. Soothes sore gums with different textures.', img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&h=800&fit=crop', options: { Set: ['Fruit Set', 'Animal Set'] } },
      { title: 'Convertible Baby Crib', type: 'Nursery', price: '299.99', compare: '380.00', tags: ['nursery', 'crib', 'furniture', 'sale'], desc: 'Solid wood 4-in-1 convertible crib. Grows from crib to toddler bed to daybed.', img: 'https://images.unsplash.com/photo-1586005780370-4f8b37e2503a?w=800&h=800&fit=crop', options: { Color: ['White', 'Natural Wood', 'Grey'] } },
      { title: 'Baby Monitor with Camera', type: 'Safety', price: '79.99', compare: '', tags: ['safety', 'monitor', 'electronics', 'best-sellers'], desc: 'HD video baby monitor with night vision, two-way audio, and temperature sensor.', img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&h=800&fit=crop', options: { Type: ['Single Camera', 'Dual Camera'] } },
      { title: 'Gentle Baby Shampoo & Wash', type: 'Bath', price: '12.99', compare: '', tags: ['bath', 'shampoo', 'gentle', 'organic'], desc: 'Tear-free organic baby shampoo and body wash. Lavender scented for calm bath time.', img: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=800&fit=crop', options: { Size: ['200ml', '400ml'] } },
      { title: 'Hooded Baby Towel Set', type: 'Bath', price: '19.99', compare: '24.00', tags: ['bath', 'towels', 'hooded', 'sale'], desc: 'Adorable animal-ear hooded towels with matching washcloths. Super absorbent bamboo cotton.', img: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=800&fit=crop', options: { Design: ['Bear', 'Bunny', 'Elephant'] } },
      { title: 'Stacking Rings Toy', type: 'Toys', price: '11.99', compare: '', tags: ['toys', 'educational', 'stacking', '6-months'], desc: 'Colorful stacking rings to develop motor skills and color recognition. BPA-free.', img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&h=800&fit=crop', options: { Type: ['Classic Rainbow', 'Pastel'] } },
      { title: 'Baby Carrier Ergonomic', type: 'Gear', price: '69.99', compare: '85.00', tags: ['gear', 'carrier', 'ergonomic', 'best-sellers', 'sale'], desc: 'Ergonomic 4-position baby carrier with lumbar support. From newborn to toddler.', img: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&h=800&fit=crop', options: { Color: ['Grey', 'Navy', 'Black'] } },
      { title: 'Cotton Sleep Sack', type: 'Bedding', price: '22.99', compare: '', tags: ['bedding', 'sleep-sack', 'cotton', 'newborn'], desc: 'Wearable blanket sleep sack for safe sleeping. TOG-rated for room temperature.', img: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800&h=800&fit=crop', options: { TOG: ['0.5 (Summer)', '1.0 (All Season)', '2.5 (Winter)'], Size: ['0-6M', '6-18M', '18-36M'] } },
      { title: 'Wooden Baby Gym', type: 'Toys', price: '49.99', compare: '', tags: ['toys', 'play-gym', 'wooden', 'montessori', 'new-arrivals'], desc: 'Scandinavian-style wooden play gym with hanging toys. Stimulates reach and grasp.', img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&h=800&fit=crop', options: { Style: ['Natural', 'Pastel'] } },
      { title: 'Baby Food Maker 4-in-1', type: 'Feeding', price: '59.99', compare: '72.00', tags: ['feeding', 'food-maker', 'weaning', 'sale'], desc: 'Steam, blend, defrost, and reheat baby food. BPA-free with one-touch controls.', img: 'https://images.unsplash.com/photo-1586005780370-4f8b37e2503a?w=800&h=800&fit=crop', options: { Color: ['White', 'Mint'] } },
      { title: 'Silicone Suction Plate Set', type: 'Feeding', price: '18.99', compare: '', tags: ['feeding', 'plates', 'silicone', 'bpa-free', 'best-sellers'], desc: 'Non-slip silicone divided plate with suction base. Dishwasher and microwave safe.', img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&h=800&fit=crop', options: { Color: ['Sage', 'Dusty Pink', 'Sky Blue', 'Grey'] } },
      { title: 'Diaper Caddy Organizer', type: 'Nursery', price: '25.99', compare: '30.00', tags: ['nursery', 'organizer', 'storage', 'new-arrivals', 'sale'], desc: 'Portable felt diaper caddy with dividers. Keeps all essentials within reach.', img: 'https://images.unsplash.com/photo-1586005780370-4f8b37e2503a?w=800&h=800&fit=crop', options: { Color: ['Grey', 'White', 'Beige'] } },
      { title: 'Baby Milestone Cards', type: 'Gifts', price: '16.99', compare: '', tags: ['gifts', 'milestone', 'keepsake', 'new-arrivals'], desc: 'Set of 30 beautifully illustrated milestone cards. Capture every precious first.', img: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&h=800&fit=crop', options: { Design: ['Woodland', 'Botanical', 'Minimal'] } },
      { title: 'Plush Night Light', type: 'Nursery', price: '21.99', compare: '', tags: ['nursery', 'night-light', 'plush', 'sleep'], desc: 'Soft plush toy with warm LED night light and auto-off timer. Comforting glow.', img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&h=800&fit=crop', options: { Animal: ['Bunny', 'Bear', 'Owl', 'Lamb'] } },
      { title: 'Infant Car Seat', type: 'Gear', price: '189.99', compare: '220.00', tags: ['gear', 'car-seat', 'safety', 'sale'], desc: 'Rear-facing infant car seat with side-impact protection. 4-35 lbs capacity.', img: 'https://images.unsplash.com/photo-1586005780370-4f8b37e2503a?w=800&h=800&fit=crop', options: { Color: ['Black', 'Grey', 'Navy'] } },
      { title: 'Soft Book Crinkle Set', type: 'Toys', price: '13.99', compare: '', tags: ['toys', 'books', 'sensory', '3-months'], desc: 'Set of 4 cloth books with crinkle pages, squeakers, and bright patterns.', img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&h=800&fit=crop', options: { Set: ['Animals', 'Shapes & Colors'] } },
      { title: 'Fitted Crib Sheet Set', type: 'Bedding', price: '19.99', compare: '24.00', tags: ['bedding', 'sheets', 'cotton', 'nursery', 'sale'], desc: 'Pack of 2 ultra-soft jersey cotton fitted crib sheets. Snug elastic edges.', img: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800&h=800&fit=crop', options: { Pattern: ['Stars/Solid', 'Animals/Solid', 'Stripes/Solid'] } },
      { title: 'Baby Nail Trimmer Electric', type: 'Care', price: '15.99', compare: '', tags: ['care', 'grooming', 'nail-trimmer', 'safety'], desc: 'Whisper-quiet electric nail trimmer with LED light. Safe for sleeping babies.', img: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=800&fit=crop', options: { Color: ['White/Pink', 'White/Blue'] } },
    ]
  },

  toys: {
    vendor: 'FlexiPlay', tags_base: ['toys', 'games'],
    products: [
      { title: 'Wooden Building Blocks 100pc', type: 'Building', price: '34.99', compare: '42.00', tags: ['building', 'wooden', 'educational', 'toddler', 'best-sellers', 'sale'], desc: '100 solid wood blocks in assorted shapes and colors. Classic open-ended play.', img: 'https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=800&h=800&fit=crop', options: { Set: ['Classic', 'Pastel'] } },
      { title: 'STEM Robot Building Kit', type: 'STEM', price: '49.99', compare: '', tags: ['stem', 'robotics', 'coding', '8-plus', 'new-arrivals'], desc: 'Build and code your own robot. 200+ pieces with app-controlled motors.', img: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&h=800&fit=crop', options: { Level: ['Beginner', 'Advanced'] } },
      { title: 'Art Supply Mega Set', type: 'Creative', price: '29.99', compare: '38.00', tags: ['creative', 'art', 'crafts', '5-plus', 'sale', 'best-sellers'], desc: '150-piece art set with crayons, markers, colored pencils, paints, and brushes.', img: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&h=800&fit=crop', options: { Set: ['Standard', 'Deluxe'] } },
      { title: 'Outdoor Explorer Kit', type: 'Outdoor', price: '24.99', compare: '', tags: ['outdoor', 'explorer', 'nature', '6-plus'], desc: 'Binoculars, compass, magnifying glass, bug catcher, and flashlight. Adventure awaits!', img: 'https://images.unsplash.com/photo-1560541919-eb5c2da6a5a3?w=800&h=800&fit=crop', options: { Color: ['Green', 'Blue'] } },
      { title: 'Family Board Game Collection', type: 'Board Games', price: '39.99', compare: '48.00', tags: ['board-games', 'family', 'strategy', '8-plus', 'sale'], desc: 'Set of 3 classic board games. Perfect for family game night.', img: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=800&h=800&fit=crop', options: { Set: ['Classic Trio', 'Strategy Trio'] } },
      { title: 'Magnetic Tile Building Set', type: 'Building', price: '44.99', compare: '', tags: ['building', 'magnetic', 'stem', 'toddler', 'best-sellers'], desc: '60-piece magnetic tiles for 3D building. Develops spatial awareness and creativity.', img: 'https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=800&h=800&fit=crop', options: { Set: ['60 Piece', '100 Piece'] } },
      { title: 'Plush Dinosaur Collection', type: 'Plush', price: '16.99', compare: '', tags: ['plush', 'dinosaurs', 'soft-toys', '3-plus'], desc: 'Cuddly dinosaur plush toy. Super-soft, huggable, and perfectly sized for little hands.', img: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&h=800&fit=crop', options: { Dino: ['T-Rex', 'Triceratops', 'Brontosaurus', 'Stegosaurus'] } },
      { title: 'Kids Science Experiment Kit', type: 'STEM', price: '32.99', compare: '40.00', tags: ['stem', 'science', 'experiments', '6-plus', 'new-arrivals', 'sale'], desc: '25 exciting experiments — volcanoes, crystals, slime, and more. Lab coat included!', img: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&h=800&fit=crop', options: { Type: ['Chemistry', 'Physics'] } },
      { title: 'Ride-On Balance Bike', type: 'Outdoor', price: '59.99', compare: '72.00', tags: ['outdoor', 'balance-bike', 'ride-on', '2-plus', 'sale'], desc: 'Lightweight balance bike with adjustable seat. Builds confidence before pedal bikes.', img: 'https://images.unsplash.com/photo-1560541919-eb5c2da6a5a3?w=800&h=800&fit=crop', options: { Color: ['Red', 'Blue', 'Pink', 'Green'] } },
      { title: 'Pretend Play Kitchen Set', type: 'Pretend Play', price: '54.99', compare: '', tags: ['pretend-play', 'kitchen', 'role-play', '3-plus'], desc: 'Wooden play kitchen with pots, pans, utensils, and play food. Imagination station!', img: 'https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=800&h=800&fit=crop', options: { Color: ['White/Pastel', 'Natural Wood'] } },
      { title: 'RC Monster Truck', type: 'Vehicles', price: '39.99', compare: '48.00', tags: ['vehicles', 'remote-control', 'rc', '6-plus', 'best-sellers', 'sale'], desc: 'All-terrain RC monster truck with 2.4GHz remote. Does flips, climbs hills, and races.', img: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&h=800&fit=crop', options: { Color: ['Red', 'Blue', 'Green'] } },
      { title: 'Puzzle Set 4-in-1', type: 'Puzzles', price: '18.99', compare: '', tags: ['puzzles', 'educational', 'toddler', '3-plus'], desc: 'Progressive jigsaw puzzles: 12, 24, 36, and 48 pieces. Grows with your child.', img: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=800&h=800&fit=crop', options: { Theme: ['Animals', 'Vehicles', 'Fairy Tales'] } },
      { title: 'Musical Instruments Set', type: 'Music', price: '27.99', compare: '34.00', tags: ['music', 'instruments', 'educational', 'toddler', 'sale'], desc: 'Set of 10 wooden instruments — xylophone, tambourine, maracas, and more.', img: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&h=800&fit=crop', options: { Set: ['Classic', 'Rainbow'] } },
      { title: 'Bubble Machine Deluxe', type: 'Outdoor', price: '19.99', compare: '', tags: ['outdoor', 'bubbles', 'summer', '3-plus', 'new-arrivals'], desc: 'Automatic bubble machine that produces hundreds of bubbles per minute. Includes solution.', img: 'https://images.unsplash.com/photo-1560541919-eb5c2da6a5a3?w=800&h=800&fit=crop', options: { Color: ['Blue', 'Pink'] } },
      { title: 'Play-Doh Mega Pack', type: 'Creative', price: '14.99', compare: '', tags: ['creative', 'play-doh', 'molding', 'toddler'], desc: '24 cans of non-toxic modeling compound in vibrant colors. Hours of squishy fun.', img: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&h=800&fit=crop', options: { Pack: ['24 Colors'] } },
      { title: 'Kids Telescope Starter', type: 'STEM', price: '42.99', compare: '52.00', tags: ['stem', 'telescope', 'space', '8-plus', 'sale'], desc: 'Beginner telescope with 40x magnification. See the moon craters and planets!', img: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&h=800&fit=crop', options: { Color: ['White', 'Black'] } },
      { title: 'Doll House Wooden', type: 'Pretend Play', price: '79.99', compare: '95.00', tags: ['pretend-play', 'dollhouse', 'wooden', '3-plus', 'sale'], desc: '3-story wooden dollhouse with 15 furniture pieces. Detailed and beautifully crafted.', img: 'https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=800&h=800&fit=crop', options: { Style: ['Classic', 'Modern'] } },
      { title: 'Water Table Activity Center', type: 'Outdoor', price: '44.99', compare: '', tags: ['outdoor', 'water-play', 'summer', 'toddler', 'best-sellers'], desc: 'Interactive water table with scoops, spinners, and water maze. Splashy summer fun.', img: 'https://images.unsplash.com/photo-1560541919-eb5c2da6a5a3?w=800&h=800&fit=crop', options: { Size: ['Standard', 'Large'] } },
      { title: 'Card Game Collection for Kids', type: 'Card Games', price: '12.99', compare: '', tags: ['card-games', 'family', 'travel', '5-plus'], desc: 'Set of 4 kid-friendly card games in a travel tin. Perfect for road trips.', img: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=800&h=800&fit=crop', options: { Set: ['Classic', 'Adventure'] } },
      { title: 'Kinetic Sand Playset', type: 'Creative', price: '22.99', compare: '28.00', tags: ['creative', 'sand', 'sensory', '3-plus', 'new-arrivals', 'sale'], desc: 'Mess-free kinetic sand with molds and tools. Squeezable, moldable, mesmerizing.', img: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&h=800&fit=crop', options: { Color: ['Natural', 'Rainbow Pack'] } },
    ]
  },

  kitchen: {
    vendor: 'FlexiChef', tags_base: ['kitchen', 'home'],
    products: [
      { title: 'Non-Stick Cookware Set 10pc', type: 'Cookware', price: '129.99', compare: '160.00', tags: ['cookware', 'non-stick', 'pots', 'pans', 'best-sellers', 'sale'], desc: '10-piece ceramic non-stick cookware set. PFOA-free, oven-safe to 450°F, dishwasher safe.', img: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=800&fit=crop', options: { Color: ['Grey', 'Cream', 'Navy'] } },
      { title: 'Chef\'s Knife 8-inch', type: 'Knives', price: '49.99', compare: '', tags: ['knives', 'chef-knife', 'stainless-steel', 'best-sellers'], desc: 'High-carbon stainless steel chef knife with ergonomic pakkawood handle. Razor sharp.', img: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=800&fit=crop', options: { Size: ['6 inch', '8 inch'] } },
      { title: 'Bamboo Cutting Board Set', type: 'Utensils', price: '29.99', compare: '36.00', tags: ['utensils', 'cutting-board', 'bamboo', 'eco', 'sale'], desc: 'Set of 3 organic bamboo cutting boards with juice grooves. Knife-friendly surface.', img: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800&h=800&fit=crop', options: { Set: ['3-Piece'] } },
      { title: 'Glass Food Storage Set 20pc', type: 'Storage', price: '39.99', compare: '48.00', tags: ['storage', 'glass', 'meal-prep', 'containers', 'sale'], desc: 'Borosilicate glass containers with leak-proof lids. Microwave, freezer, and oven safe.', img: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&h=800&fit=crop', options: { Set: ['10-Piece', '20-Piece'] } },
      { title: 'Cast Iron Skillet 12-inch', type: 'Cookware', price: '44.99', compare: '', tags: ['cookware', 'cast-iron', 'skillet', 'best-sellers'], desc: 'Pre-seasoned cast iron skillet for perfect searing. Gets better with every use.', img: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=800&fit=crop', options: { Size: ['10 inch', '12 inch'] } },
      { title: 'Silicone Utensil Set 12pc', type: 'Utensils', price: '24.99', compare: '30.00', tags: ['utensils', 'silicone', 'cooking-tools', 'sale'], desc: 'Heat-resistant silicone utensils with wooden handles. Won\'t scratch non-stick surfaces.', img: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800&h=800&fit=crop', options: { Color: ['Black', 'Grey', 'Teal'] } },
      { title: 'Pour-Over Coffee Maker', type: 'Beverages', price: '34.99', compare: '', tags: ['beverages', 'coffee', 'pour-over', 'new-arrivals'], desc: 'Elegant borosilicate glass pour-over coffee maker with reusable steel filter.', img: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=800&fit=crop', options: { Size: ['3 Cup', '6 Cup'] } },
      { title: 'Stainless Steel Mixing Bowls', type: 'Baking', price: '27.99', compare: '34.00', tags: ['baking', 'mixing-bowls', 'stainless-steel', 'sale'], desc: 'Set of 5 nesting mixing bowls with non-slip bases and measurement markings.', img: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=800&fit=crop', options: { Set: ['5-Piece'] } },
      { title: 'Electric Spice Grinder', type: 'Appliances', price: '22.99', compare: '', tags: ['appliances', 'spice-grinder', 'electric'], desc: 'One-touch electric grinder for spices, herbs, and coffee beans. Stainless steel blades.', img: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&h=800&fit=crop', options: { Color: ['Silver', 'Black'] } },
      { title: 'Baking Sheet & Rack Set', type: 'Baking', price: '19.99', compare: '24.00', tags: ['baking', 'sheet-pan', 'baking-rack', 'sale'], desc: 'Heavy-duty aluminum baking sheets with cooling racks. Warp-resistant at high temps.', img: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=800&fit=crop', options: { Size: ['Half Sheet', 'Quarter Sheet'] } },
      { title: 'Digital Kitchen Scale', type: 'Gadgets', price: '18.99', compare: '', tags: ['gadgets', 'scale', 'digital', 'baking', 'best-sellers'], desc: 'Precise digital kitchen scale with tare function. Essential for perfect baking.', img: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&h=800&fit=crop', options: { Color: ['Silver', 'Black', 'White'] } },
      { title: 'Insulated Water Bottle', type: 'Beverages', price: '24.99', compare: '', tags: ['beverages', 'water-bottle', 'insulated', 'eco', 'new-arrivals'], desc: 'Double-wall vacuum insulated bottle. Cold 24 hours, hot 12 hours. BPA-free.', img: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&h=800&fit=crop', options: { Color: ['Matte Black', 'White', 'Rose Gold'], Size: ['500ml', '750ml', '1L'] } },
      { title: 'Spice Rack Organizer', type: 'Storage', price: '32.99', compare: '40.00', tags: ['storage', 'spice-rack', 'organizer', 'sale'], desc: 'Rotating bamboo spice rack with 16 labeled glass jars. Keeps counter tidy.', img: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&h=800&fit=crop', options: { Type: ['16 Jar', '24 Jar'] } },
      { title: 'Knife Block Set 14pc', type: 'Knives', price: '89.99', compare: '110.00', tags: ['knives', 'knife-set', 'block', 'stainless-steel', 'sale'], desc: '14-piece knife set with acacia wood block. Full tang, forged stainless steel.', img: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=800&fit=crop', options: { Block: ['Acacia', 'Walnut'] } },
      { title: 'Pasta Maker Manual', type: 'Gadgets', price: '42.99', compare: '', tags: ['gadgets', 'pasta-maker', 'manual', 'new-arrivals'], desc: 'Classic hand-crank pasta machine with adjustable thickness. Fresh pasta in minutes.', img: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=800&fit=crop', options: { Type: ['Chrome'] } },
      { title: 'Dutch Oven Enameled 6qt', type: 'Cookware', price: '59.99', compare: '75.00', tags: ['cookware', 'dutch-oven', 'enameled', 'sale', 'best-sellers'], desc: 'Enameled cast iron Dutch oven. Braising, soups, stews, and bread baking.', img: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=800&fit=crop', options: { Color: ['Red', 'Navy', 'White', 'Black'], Size: ['4qt', '6qt'] } },
      { title: 'Tea Infuser Set', type: 'Beverages', price: '16.99', compare: '', tags: ['beverages', 'tea', 'infuser', 'gift'], desc: 'Set of 4 stainless steel tea infusers in fun shapes. Loose-leaf tea made easy.', img: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800&h=800&fit=crop', options: { Set: ['Classic', 'Fun Shapes'] } },
      { title: 'Linen Table Napkins Set', type: 'Dining', price: '21.99', compare: '26.00', tags: ['dining', 'napkins', 'linen', 'eco', 'sale'], desc: 'Set of 6 pure linen napkins. Machine washable, gets softer with every wash.', img: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800&h=800&fit=crop', options: { Color: ['Natural', 'White', 'Sage', 'Dusty Rose'] } },
      { title: 'Mandoline Slicer Pro', type: 'Gadgets', price: '28.99', compare: '35.00', tags: ['gadgets', 'slicer', 'mandoline', 'prep', 'sale'], desc: 'Adjustable mandoline slicer with 5 blade inserts and safety hand guard.', img: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&h=800&fit=crop', options: { Color: ['White', 'Black'] } },
      { title: 'Ceramic Dinnerware Set 16pc', type: 'Dining', price: '69.99', compare: '85.00', tags: ['dining', 'dinnerware', 'ceramic', 'best-sellers', 'sale'], desc: 'Handcrafted ceramic dinnerware for 4. Plates, bowls, and mugs in reactive glaze.', img: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800&h=800&fit=crop', options: { Color: ['Speckled White', 'Ocean Blue', 'Forest Green'] } },
    ]
  },

  sports: {
    vendor: 'FlexiFit', tags_base: ['sports', 'fitness'],
    products: [
      { title: 'Premium Yoga Mat 6mm', type: 'Yoga', price: '39.99', compare: '50.00', tags: ['yoga', 'mat', 'non-slip', 'best-sellers', 'sale'], desc: 'Non-slip TPE yoga mat with alignment lines. Extra-thick for joint protection.', img: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800&h=800&fit=crop', options: { Color: ['Purple', 'Teal', 'Black', 'Pink'] } },
      { title: 'Adjustable Dumbbell Set', type: 'Weights', price: '149.99', compare: '180.00', tags: ['weights', 'dumbbells', 'strength', 'home-gym', 'sale'], desc: 'Adjustable dumbbells 5-52.5 lbs each. Replaces 15 sets of weights in one.', img: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=800&fit=crop', options: { Set: ['Single', 'Pair'] } },
      { title: 'Resistance Bands Set 5pc', type: 'Accessories', price: '19.99', compare: '26.00', tags: ['accessories', 'resistance-bands', 'rehab', 'best-sellers', 'sale'], desc: '5 resistance levels with door anchor, handles, and ankle straps. Full body workouts.', img: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop', options: { Set: ['Standard', 'Heavy Duty'] } },
      { title: 'Running Compression Leggings', type: 'Apparel', price: '44.99', compare: '', tags: ['apparel', 'leggings', 'running', 'women', 'best-sellers'], desc: 'High-waist compression leggings with side pockets. Moisture-wicking 4-way stretch.', img: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=800&fit=crop', options: { Color: ['Black', 'Navy', 'Grey', 'Wine'], Size: ['XS', 'S', 'M', 'L', 'XL'] } },
      { title: 'Jump Rope Speed Pro', type: 'Cardio', price: '14.99', compare: '', tags: ['cardio', 'jump-rope', 'hiit', 'portable'], desc: 'Weighted speed jump rope with ball bearings. Adjustable cable for any height.', img: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800&h=800&fit=crop', options: { Color: ['Black', 'Red'] } },
      { title: 'Foam Roller Muscle Recovery', type: 'Recovery', price: '24.99', compare: '30.00', tags: ['recovery', 'foam-roller', 'massage', 'sale'], desc: 'High-density foam roller with textured zones. Relieves tension and speeds recovery.', img: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop', options: { Size: ['13 inch', '18 inch', '36 inch'] } },
      { title: 'Men\'s Training T-Shirt', type: 'Apparel', price: '29.99', compare: '', tags: ['apparel', 'training', 'men', 'moisture-wicking'], desc: 'Lightweight moisture-wicking training tee. Anti-odor technology for intense sessions.', img: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=800&fit=crop', options: { Color: ['Black', 'Grey', 'Navy', 'White'], Size: ['S', 'M', 'L', 'XL', 'XXL'] } },
      { title: 'Protein Shaker Bottle', type: 'Accessories', price: '12.99', compare: '', tags: ['accessories', 'shaker', 'supplements', 'gym'], desc: 'Leak-proof shaker bottle with mixing ball and supplement storage. BPA-free.', img: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop', options: { Color: ['Black', 'Clear/Blue', 'Clear/Green'], Size: ['24oz', '28oz'] } },
      { title: 'Kettlebell Cast Iron', type: 'Weights', price: '34.99', compare: '', tags: ['weights', 'kettlebell', 'strength', 'home-gym'], desc: 'Single-cast iron kettlebell with vinyl coating. Wide handle for comfortable grip.', img: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=800&fit=crop', options: { Weight: ['15 lb', '25 lb', '35 lb', '50 lb'] } },
      { title: 'Gym Duffel Bag', type: 'Bags', price: '39.99', compare: '48.00', tags: ['bags', 'gym-bag', 'duffel', 'sale'], desc: 'Water-resistant gym duffel with shoe compartment and wet pocket. Fits everything.', img: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop', options: { Color: ['Black', 'Grey', 'Navy'] } },
      { title: 'Pull-Up Bar Doorway', type: 'Equipment', price: '29.99', compare: '36.00', tags: ['equipment', 'pull-up-bar', 'home-gym', 'strength', 'sale'], desc: 'No-screw doorway pull-up bar with foam grips. Multiple grip positions.', img: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800&h=800&fit=crop', options: { Size: ['Standard (26-36 in)', 'Wide (36-44 in)'] } },
      { title: 'Whey Protein Powder 2lb', type: 'Supplements', price: '34.99', compare: '', tags: ['supplements', 'protein', 'whey', 'recovery', 'best-sellers'], desc: '25g protein per scoop. Grass-fed whey isolate with zero artificial sweeteners.', img: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop', options: { Flavor: ['Chocolate', 'Vanilla', 'Strawberry', 'Unflavored'] } },
      { title: 'Sports Bra High Impact', type: 'Apparel', price: '34.99', compare: '', tags: ['apparel', 'sports-bra', 'women', 'high-impact', 'new-arrivals'], desc: 'High-impact sports bra with adjustable straps and moisture management. Bounce-free.', img: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=800&fit=crop', options: { Color: ['Black', 'Grey', 'White', 'Coral'], Size: ['XS', 'S', 'M', 'L', 'XL'] } },
      { title: 'Ab Roller Wheel', type: 'Equipment', price: '17.99', compare: '22.00', tags: ['equipment', 'abs', 'core', 'home-gym', 'sale'], desc: 'Dual-wheel ab roller with knee pad. Builds core strength with proper form.', img: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800&h=800&fit=crop', options: { Color: ['Black/Red', 'Black/Blue'] } },
      { title: 'Running Shorts Quick-Dry', type: 'Apparel', price: '26.99', compare: '', tags: ['apparel', 'shorts', 'running', 'men', 'quick-dry'], desc: 'Lightweight running shorts with built-in liner and zip pocket. Ultra-breathable.', img: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=800&fit=crop', options: { Color: ['Black', 'Navy', 'Grey'], Size: ['S', 'M', 'L', 'XL'] } },
      { title: 'Exercise Ball Anti-Burst', type: 'Equipment', price: '22.99', compare: '', tags: ['equipment', 'exercise-ball', 'core', 'yoga'], desc: 'Anti-burst stability ball with pump. Perfect for core work, stretching, and sitting.', img: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800&h=800&fit=crop', options: { Size: ['55cm', '65cm', '75cm'] } },
      { title: 'Creatine Monohydrate', type: 'Supplements', price: '24.99', compare: '30.00', tags: ['supplements', 'creatine', 'strength', 'sale'], desc: 'Pure micronized creatine monohydrate. 5g per scoop, 60 servings. No fillers.', img: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop', options: { Flavor: ['Unflavored', 'Fruit Punch'] } },
      { title: 'Workout Gloves Padded', type: 'Accessories', price: '18.99', compare: '', tags: ['accessories', 'gloves', 'gym', 'grip', 'new-arrivals'], desc: 'Padded gym gloves with wrist support. Better grip, fewer calluses.', img: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop', options: { Size: ['S', 'M', 'L', 'XL'] } },
      { title: 'Yoga Block Set of 2', type: 'Yoga', price: '15.99', compare: '', tags: ['yoga', 'blocks', 'props', 'flexibility'], desc: 'High-density EVA foam yoga blocks. Essential props for deeper stretches.', img: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800&h=800&fit=crop', options: { Color: ['Purple', 'Cork', 'Blue', 'Black'] } },
      { title: 'Fitness Tracker Smart Watch', type: 'Wearables', price: '69.99', compare: '85.00', tags: ['wearables', 'fitness-tracker', 'smartwatch', 'new-arrivals', 'sale'], desc: 'GPS fitness watch with heart rate, blood oxygen, sleep tracking, and 7-day battery.', img: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop', options: { Color: ['Black', 'Grey', 'Rose Gold'] } },
    ]
  },

  food: {
    vendor: 'FlexiHarvest', tags_base: ['food', 'grocery'],
    products: [
      { title: 'Artisan Dark Chocolate Box', type: 'Snacks', price: '24.99', compare: '30.00', tags: ['snacks', 'chocolate', 'artisan', 'gift', 'best-sellers', 'sale'], desc: 'Box of 12 single-origin dark chocolate truffles. Handcrafted by master chocolatiers.', img: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800&h=800&fit=crop', options: { Type: ['Dark 70%', 'Assorted', 'Sea Salt'] } },
      { title: 'Premium Spice Collection', type: 'Spices', price: '34.99', compare: '', tags: ['spices', 'collection', 'organic', 'best-sellers'], desc: 'Set of 8 organic whole spices in glass jars. Freshly sourced from around the world.', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop', options: { Set: ['Global Kitchen', 'BBQ Master', 'Indian Essentials'] } },
      { title: 'Organic Extra Virgin Olive Oil', type: 'Oils', price: '18.99', compare: '22.00', tags: ['oils', 'olive-oil', 'organic', 'cooking', 'sale'], desc: 'Cold-pressed organic EVOO from small-batch Mediterranean farms. Rich and fruity.', img: 'https://images.unsplash.com/photo-1474979266404-7f28db5c5e67?w=800&h=800&fit=crop', options: { Size: ['250ml', '500ml', '1L'] } },
      { title: 'Mixed Nuts & Trail Mix', type: 'Snacks', price: '14.99', compare: '', tags: ['snacks', 'nuts', 'trail-mix', 'healthy'], desc: 'Premium roasted mixed nuts with dried fruits. No added sugar or preservatives.', img: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800&h=800&fit=crop', options: { Flavor: ['Classic', 'Tropical', 'Dark Chocolate'], Size: ['200g', '500g'] } },
      { title: 'Organic Honey Raw Unfiltered', type: 'Sweeteners', price: '16.99', compare: '20.00', tags: ['sweeteners', 'honey', 'organic', 'raw', 'sale'], desc: 'Raw unfiltered wildflower honey from local apiaries. Rich flavor with natural enzymes.', img: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=800&fit=crop', options: { Size: ['250g', '500g'] } },
      { title: 'Loose Leaf Tea Collection', type: 'Beverages', price: '22.99', compare: '', tags: ['beverages', 'tea', 'loose-leaf', 'organic', 'best-sellers'], desc: 'Curated box of 6 organic loose-leaf teas from Japan, India, and China. 60 cups.', img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=800&fit=crop', options: { Set: ['Classic', 'Herbal', 'Green & White'] } },
      { title: 'Artisan Pasta Variety Pack', type: 'Pantry', price: '19.99', compare: '24.00', tags: ['pantry', 'pasta', 'artisan', 'italian', 'sale'], desc: 'Bronze-die cut Italian pasta in 4 shapes. Slow-dried for superior texture and flavor.', img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=800&fit=crop', options: { Pack: ['Classic Shapes', 'Special Shapes'] } },
      { title: 'Hot Sauce Trio Gift Set', type: 'Condiments', price: '21.99', compare: '', tags: ['condiments', 'hot-sauce', 'gift', 'new-arrivals'], desc: 'Three small-batch hot sauces: Mild, Medium, and Inferno. Natural ingredients only.', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop', options: { Set: ['Original Trio', 'Smoky Trio'] } },
      { title: 'Granola Clusters Organic', type: 'Breakfast', price: '9.99', compare: '', tags: ['breakfast', 'granola', 'organic', 'healthy'], desc: 'Crunchy oat clusters with almonds and dark chocolate. Low sugar, high fiber.', img: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=800&fit=crop', options: { Flavor: ['Chocolate Almond', 'Maple Pecan', 'Berry Coconut'] } },
      { title: 'Single Origin Coffee Beans', type: 'Coffee', price: '17.99', compare: '21.00', tags: ['coffee', 'beans', 'single-origin', 'best-sellers', 'sale'], desc: 'Freshly roasted single-origin beans. Medium roast with notes of caramel and cocoa.', img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=800&fit=crop', options: { Origin: ['Ethiopian', 'Colombian', 'Guatemalan'], Size: ['250g', '500g', '1kg'] } },
      { title: 'Dried Fruit & Nut Bars 12-pack', type: 'Snacks', price: '18.99', compare: '22.00', tags: ['snacks', 'bars', 'healthy', 'gluten-free', 'sale'], desc: 'Whole food energy bars with just fruit, nuts, and seeds. Gluten-free, vegan.', img: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800&h=800&fit=crop', options: { Flavor: ['Cashew Date', 'Almond Fig', 'Coconut Mango'] } },
      { title: 'Balsamic Vinegar Aged', type: 'Oils', price: '14.99', compare: '', tags: ['oils', 'vinegar', 'balsamic', 'italian'], desc: 'Aged balsamic vinegar of Modena. Rich, complex sweetness for salads and finishing.', img: 'https://images.unsplash.com/photo-1474979266404-7f28db5c5e67?w=800&h=800&fit=crop', options: { Age: ['5 Year', '10 Year'] } },
      { title: 'Organic Matcha Powder', type: 'Beverages', price: '24.99', compare: '30.00', tags: ['beverages', 'matcha', 'organic', 'japanese', 'new-arrivals', 'sale'], desc: 'Ceremonial grade organic matcha from Kyoto. Vibrant green, smooth, and energizing.', img: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=800&fit=crop', options: { Size: ['30g Tin', '100g Bag'] } },
      { title: 'Gourmet Popcorn Variety Pack', type: 'Snacks', price: '16.99', compare: '', tags: ['snacks', 'popcorn', 'gourmet', 'gift'], desc: '6 flavors of hand-popped gourmet popcorn. From classic butter to truffle parmesan.', img: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800&h=800&fit=crop', options: { Pack: ['6 Flavor Mix', 'Savory Collection', 'Sweet Collection'] } },
      { title: 'Himalayan Pink Salt Set', type: 'Spices', price: '12.99', compare: '15.00', tags: ['spices', 'salt', 'himalayan', 'cooking', 'sale'], desc: 'Fine and coarse Himalayan pink salt set with grinder. 84 trace minerals.', img: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop', options: { Set: ['Fine + Coarse', 'Fine + Grinder'] } },
      { title: 'Subscription Snack Box', type: 'Subscription', price: '29.99', compare: '', tags: ['subscription', 'snack-box', 'curated', 'new-arrivals', 'best-sellers'], desc: 'Monthly curated box of 10-12 artisan snacks from around the world. Surprise every month!', img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=800&fit=crop', options: { Plan: ['Monthly', 'Quarterly'] } },
      { title: 'Nut Butter Trio', type: 'Pantry', price: '19.99', compare: '24.00', tags: ['pantry', 'nut-butter', 'organic', 'spread', 'sale'], desc: 'Organic almond, cashew, and peanut butter trio. Stone-ground, no added sugar.', img: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=800&fit=crop', options: { Set: ['Classic Trio', 'Crunchy Trio'] } },
      { title: 'Coconut Oil Virgin Organic', type: 'Oils', price: '11.99', compare: '', tags: ['oils', 'coconut-oil', 'organic', 'cooking', 'keto'], desc: 'Cold-pressed virgin coconut oil. Cooking, baking, smoothies, and skin care.', img: 'https://images.unsplash.com/photo-1474979266404-7f28db5c5e67?w=800&h=800&fit=crop', options: { Size: ['250ml', '500ml'] } },
      { title: 'Dried Mango Slices Organic', type: 'Snacks', price: '8.99', compare: '', tags: ['snacks', 'dried-fruit', 'mango', 'organic', 'vegan'], desc: 'Sun-dried organic mango slices with no added sugar. Sweet, chewy tropical treat.', img: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800&h=800&fit=crop', options: { Size: ['100g', '250g'] } },
      { title: 'Ceramic Coffee Mug Set', type: 'Drinkware', price: '26.99', compare: '32.00', tags: ['drinkware', 'mugs', 'ceramic', 'gift', 'sale'], desc: 'Set of 4 handmade ceramic mugs in reactive glaze. Each one beautifully unique.', img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=800&fit=crop', options: { Color: ['Earth Tones', 'Ocean Blues', 'Neutrals'] } },
    ]
  },

  furniture: {
    vendor: 'FlexiHome', tags_base: ['furniture', 'decor'],
    products: [
      { title: 'Mid-Century Modern Sofa', type: 'Living Room', price: '699.99', compare: '850.00', tags: ['living-room', 'sofa', 'mid-century', 'best-sellers', 'sale'], desc: '3-seater sofa with walnut tapered legs and tufted cushions. Timeless mid-century style.', img: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=800&fit=crop', options: { Color: ['Grey', 'Navy', 'Green', 'Mustard'] } },
      { title: 'Scandinavian Dining Table', type: 'Dining', price: '449.99', compare: '', tags: ['dining', 'table', 'scandinavian', 'wood', 'new-arrivals'], desc: 'Solid oak dining table with clean lines. Seats 6 comfortably. Easy assembly.', img: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=800&fit=crop', options: { Size: ['4-Seat', '6-Seat'], Finish: ['Natural Oak', 'Walnut'] } },
      { title: 'Upholstered Bed Frame Queen', type: 'Bedroom', price: '399.99', compare: '480.00', tags: ['bedroom', 'bed-frame', 'upholstered', 'sale'], desc: 'Padded upholstered bed frame with wingback headboard. Noise-free slat support.', img: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=800&fit=crop', options: { Color: ['Light Grey', 'Beige', 'Dark Grey'], Size: ['Queen', 'King'] } },
      { title: 'Floating Wall Shelves Set', type: 'Home Decor', price: '39.99', compare: '48.00', tags: ['home-decor', 'shelves', 'floating', 'wall-mount', 'sale'], desc: 'Set of 3 floating shelves in solid wood. Hidden bracket design for clean look.', img: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop', options: { Finish: ['Walnut', 'White', 'Natural Oak'] } },
      { title: 'Accent Armchair Velvet', type: 'Living Room', price: '299.99', compare: '', tags: ['living-room', 'armchair', 'velvet', 'accent', 'best-sellers'], desc: 'Luxurious velvet accent chair with gold-finished legs. Statement piece for any room.', img: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=800&fit=crop', options: { Color: ['Emerald', 'Blush', 'Navy', 'Mustard'] } },
      { title: 'Industrial Bookshelf 5-Tier', type: 'Living Room', price: '179.99', compare: '210.00', tags: ['living-room', 'bookshelf', 'industrial', 'storage', 'sale'], desc: 'Metal and wood industrial bookshelf. 5 tiers for books, plants, and display.', img: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop', options: { Finish: ['Black/Rustic', 'Black/Walnut'] } },
      { title: 'Coffee Table Marble Top', type: 'Living Room', price: '249.99', compare: '', tags: ['living-room', 'coffee-table', 'marble', 'new-arrivals'], desc: 'Round marble-top coffee table with brass legs. Elegant centerpiece for your living room.', img: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=800&fit=crop', options: { Marble: ['White', 'Green', 'Black'] } },
      { title: 'Rattan Pendant Light', type: 'Home Decor', price: '69.99', compare: '82.00', tags: ['home-decor', 'lighting', 'rattan', 'boho', 'sale'], desc: 'Handwoven rattan pendant light with warm ambient glow. Bohemian chic statement.', img: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop', options: { Size: ['Small 12 in', 'Medium 16 in', 'Large 20 in'] } },
      { title: 'Memory Foam Mattress Queen', type: 'Bedroom', price: '499.99', compare: '620.00', tags: ['bedroom', 'mattress', 'memory-foam', 'best-sellers', 'sale'], desc: '10-inch gel memory foam mattress. CertiPUR-US certified. 100-night trial.', img: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=800&fit=crop', options: { Size: ['Twin', 'Full', 'Queen', 'King'] } },
      { title: 'Bar Stools Set of 2', type: 'Dining', price: '159.99', compare: '', tags: ['dining', 'bar-stools', 'counter-height', 'modern'], desc: 'Set of 2 modern bar stools with footrest. Swivel seat and adjustable height.', img: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=800&fit=crop', options: { Color: ['Black', 'White', 'Grey'] } },
      { title: 'Linen Throw Pillows Set', type: 'Home Decor', price: '34.99', compare: '42.00', tags: ['home-decor', 'pillows', 'linen', 'throw', 'sale'], desc: 'Set of 2 linen throw pillows with hidden zipper. Soft, textured, machine washable.', img: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop', options: { Color: ['Sage', 'Terracotta', 'Cream', 'Dusty Blue'], Size: ['18x18', '20x20'] } },
      { title: 'Nightstand with Drawer', type: 'Bedroom', price: '129.99', compare: '', tags: ['bedroom', 'nightstand', 'wood', 'storage'], desc: 'Minimalist nightstand with drawer and open shelf. Solid pine with tapered legs.', img: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=800&fit=crop', options: { Finish: ['Natural', 'Walnut', 'White'] } },
      { title: 'Area Rug Handwoven 5x7', type: 'Home Decor', price: '149.99', compare: '180.00', tags: ['home-decor', 'rug', 'handwoven', 'boho', 'sale'], desc: 'Handwoven cotton and jute area rug. Natural textures add warmth to any room.', img: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop', options: { Size: ['3x5', '5x7', '8x10'], Pattern: ['Natural Stripe', 'Diamond', 'Solid'] } },
      { title: 'Desk Home Office', type: 'Office', price: '229.99', compare: '270.00', tags: ['office', 'desk', 'home-office', 'modern', 'sale'], desc: 'Modern writing desk with 2 drawers and cable management. Work from home in style.', img: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=800&fit=crop', options: { Finish: ['White/Oak', 'Black/Walnut'] } },
      { title: 'Ceramic Table Lamp', type: 'Home Decor', price: '54.99', compare: '', tags: ['home-decor', 'lamp', 'ceramic', 'lighting', 'new-arrivals'], desc: 'Handmade ceramic base table lamp with linen shade. Warm ambient lighting.', img: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop', options: { Color: ['White', 'Sage', 'Terracotta', 'Navy'] } },
      { title: 'TV Console Mid-Century', type: 'Living Room', price: '349.99', compare: '420.00', tags: ['living-room', 'tv-stand', 'mid-century', 'media', 'sale'], desc: 'Walnut TV console with sliding doors and cable management. Fits up to 65-inch TVs.', img: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=800&fit=crop', options: { Finish: ['Walnut', 'White/Oak'] } },
      { title: 'Woven Storage Baskets Set', type: 'Home Decor', price: '29.99', compare: '', tags: ['home-decor', 'baskets', 'storage', 'woven', 'boho'], desc: 'Set of 3 handwoven seagrass baskets. Stylish storage for blankets, toys, or laundry.', img: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop', options: { Set: ['Natural', 'Black & White'] } },
      { title: 'Dining Chairs Set of 4', type: 'Dining', price: '279.99', compare: '340.00', tags: ['dining', 'chairs', 'modern', 'set', 'sale'], desc: 'Set of 4 molded chairs with solid beech legs. Comfortable and stackable.', img: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=800&fit=crop', options: { Color: ['White', 'Black', 'Grey', 'Sage'] } },
      { title: 'Faux Eucalyptus Stems', type: 'Home Decor', price: '19.99', compare: '', tags: ['home-decor', 'plants', 'faux', 'greenery'], desc: 'Set of 6 realistic faux eucalyptus stems. No watering, forever green and beautiful.', img: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&h=800&fit=crop', options: { Type: ['Silver Dollar', 'Seeded', 'Mixed'] } },
      { title: 'Ottoman Storage Bench', type: 'Living Room', price: '119.99', compare: '140.00', tags: ['living-room', 'ottoman', 'storage', 'bench', 'new-arrivals', 'sale'], desc: 'Upholstered storage ottoman/bench. Lid lifts for hidden blanket and pillow storage.', img: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=800&fit=crop', options: { Color: ['Grey', 'Beige', 'Navy'], Size: ['36 inch', '48 inch'] } },
    ]
  },

  beauty: {
    vendor: 'FlexiGlow', tags_base: ['beauty', 'skincare'],
    products: [
      { title: 'Hydrating Vitamin C Serum', type: 'Skincare', price: '38.99', compare: '48.00', tags: ['skincare', 'serum', 'vitamin-c', 'best-sellers', 'sale'], desc: 'Brightening vitamin C serum with hyaluronic acid. Reduces dark spots and boosts radiance.', img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop', options: { Size: ['15ml', '30ml'] } },
      { title: 'Daily Moisturizer SPF 30', type: 'Skincare', price: '29.99', compare: '', tags: ['skincare', 'moisturizer', 'spf', 'daily', 'best-sellers'], desc: 'Lightweight daily moisturizer with broad-spectrum SPF 30. Hydrates and protects.', img: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=800&fit=crop', options: { Type: ['Normal/Oily', 'Dry/Sensitive'] } },
      { title: 'Gentle Foaming Cleanser', type: 'Skincare', price: '22.99', compare: '28.00', tags: ['skincare', 'cleanser', 'gentle', 'sale'], desc: 'pH-balanced foaming cleanser that removes impurities without stripping moisture.', img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&h=800&fit=crop', options: { Size: ['120ml', '200ml'] } },
      { title: 'Matte Liquid Lipstick Set', type: 'Makeup', price: '34.99', compare: '45.00', tags: ['makeup', 'lipstick', 'matte', 'sale'], desc: 'Long-lasting matte liquid lipstick in 4 universally flattering shades. Cruelty-free.', img: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&h=800&fit=crop', options: { Set: ['Nudes', 'Bold', 'Berry'] } },
      { title: 'Volumizing Mascara', type: 'Makeup', price: '19.99', compare: '', tags: ['makeup', 'mascara', 'eyes'], desc: 'Buildable volumizing mascara for dramatic lashes. Smudge-proof and clump-free.', img: 'https://images.unsplash.com/photo-1631214500115-598fc2cb8ada?w=800&h=800&fit=crop', options: { Color: ['Jet Black', 'Brown'] } },
      { title: 'Repairing Hair Oil', type: 'Hair Care', price: '26.99', compare: '32.00', tags: ['hair-care', 'oil', 'repair', 'sale'], desc: 'Nourishing argan and jojoba hair oil. Tames frizz, repairs damage, adds shine.', img: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&h=800&fit=crop', options: { Size: ['50ml', '100ml'] } },
      { title: 'Exfoliating Face Scrub', type: 'Skincare', price: '24.99', compare: '', tags: ['skincare', 'exfoliant', 'scrub'], desc: 'Gentle exfoliating scrub with walnut shell and aloe vera. Smoother, brighter skin.', img: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&h=800&fit=crop', options: { Size: ['75ml', '150ml'] } },
      { title: 'Illuminating Foundation', type: 'Makeup', price: '32.99', compare: '40.00', tags: ['makeup', 'foundation', 'glow', 'sale'], desc: 'Buildable coverage foundation with natural illuminating finish. 12 inclusive shades.', img: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&h=800&fit=crop', options: { Shade: ['Fair', 'Light', 'Medium', 'Tan', 'Deep', 'Rich'] } },
      { title: 'Hydrating Sheet Mask Pack', type: 'Skincare', price: '18.99', compare: '', tags: ['skincare', 'mask', 'hydrating', 'new-arrivals'], desc: 'Pack of 5 ultra-hydrating sheet masks with ceramides and green tea extract.', img: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800&h=800&fit=crop', options: { Type: ['Hydrating', 'Brightening', 'Soothing'] } },
      { title: 'Curl Defining Cream', type: 'Hair Care', price: '21.99', compare: '27.00', tags: ['hair-care', 'curls', 'styling', 'sale'], desc: 'Lightweight curl cream that enhances natural curls without crunch or stiffness.', img: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&h=800&fit=crop', options: { Size: ['150ml', '300ml'] } },
      { title: 'Retinol Night Cream', type: 'Skincare', price: '44.99', compare: '55.00', tags: ['skincare', 'retinol', 'anti-aging', 'night-cream', 'new-arrivals', 'sale'], desc: 'Encapsulated retinol night cream for fine lines and wrinkles. Gentle yet effective.', img: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&h=800&fit=crop', options: { Strength: ['0.25% (Beginner)', '0.5% (Regular)', '1.0% (Advanced)'] } },
      { title: 'Eyebrow Pencil Micro', type: 'Makeup', price: '14.99', compare: '', tags: ['makeup', 'eyebrows', 'pencil', 'best-sellers'], desc: 'Ultra-fine micro tip eyebrow pencil for natural hair-like strokes. Built-in spoolie.', img: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&h=800&fit=crop', options: { Shade: ['Blonde', 'Brunette', 'Dark Brown', 'Black'] } },
      { title: 'Micellar Cleansing Water', type: 'Skincare', price: '16.99', compare: '', tags: ['skincare', 'cleanser', 'micellar', 'gentle'], desc: 'No-rinse micellar water that removes makeup and impurities in one step. All skin types.', img: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=800&fit=crop', options: { Size: ['200ml', '400ml'] } },
      { title: 'Setting Spray Matte Finish', type: 'Makeup', price: '17.99', compare: '22.00', tags: ['makeup', 'setting-spray', 'matte', 'sale'], desc: 'Lock in your look for 16 hours. Oil-control matte finish setting spray.', img: 'https://images.unsplash.com/photo-1631214500115-598fc2cb8ada?w=800&h=800&fit=crop', options: { Size: ['60ml', '120ml'] } },
      { title: 'Sulfate-Free Shampoo', type: 'Hair Care', price: '18.99', compare: '', tags: ['hair-care', 'shampoo', 'sulfate-free', 'color-safe'], desc: 'Gentle sulfate-free shampoo for color-treated hair. Preserves vibrancy and moisture.', img: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&h=800&fit=crop', options: { Size: ['250ml', '500ml'] } },
      { title: 'Lip Gloss Plumping', type: 'Makeup', price: '15.99', compare: '', tags: ['makeup', 'lip-gloss', 'plumping', 'new-arrivals'], desc: 'High-shine plumping lip gloss with peptides. Fuller-looking lips in minutes.', img: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&h=800&fit=crop', options: { Shade: ['Clear', 'Pink Nude', 'Berry', 'Mauve'] } },
      { title: 'Clay Detox Face Mask', type: 'Skincare', price: '19.99', compare: '24.00', tags: ['skincare', 'mask', 'clay', 'detox', 'sale'], desc: 'Kaolin clay mask with charcoal and tea tree. Deep cleans pores in 10 minutes.', img: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&h=800&fit=crop', options: { Size: ['60ml', '120ml'] } },
      { title: 'Makeup Brush Set 12pc', type: 'Tools', price: '29.99', compare: '38.00', tags: ['tools', 'brushes', 'makeup-brushes', 'best-sellers', 'sale'], desc: 'Professional 12-piece brush set with vegan bristles and faux leather case.', img: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&h=800&fit=crop', options: { Color: ['Rose Gold', 'Black', 'White'] } },
      { title: 'Deep Conditioning Hair Mask', type: 'Hair Care', price: '23.99', compare: '', tags: ['hair-care', 'mask', 'conditioning', 'repair'], desc: 'Intensive deep conditioning mask with keratin and coconut oil. 5 minutes to silky hair.', img: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&h=800&fit=crop', options: { Size: ['150ml', '300ml'] } },
      { title: 'Skincare Gift Set', type: 'Gift Sets', price: '59.99', compare: '75.00', tags: ['gift-sets', 'skincare', 'gift', 'new-arrivals', 'sale'], desc: 'Complete skincare routine in a gift box: cleanser, serum, moisturizer, and eye cream.', img: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=800&fit=crop', options: { Type: ['Normal Skin', 'Dry Skin', 'Oily Skin'] } },
    ]
  },

  electronics: {
    vendor: 'FlexiTech', tags_base: ['electronics', 'tech'],
    products: [
      { title: 'Wireless Noise-Cancelling Headphones', type: 'Audio', price: '79.99', compare: '99.99', tags: ['audio', 'headphones', 'wireless', 'noise-cancelling', 'best-sellers', 'sale'], desc: 'Premium ANC headphones with 30-hour battery and crystal-clear sound.', img: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop', options: { Color: ['Matte Black', 'White', 'Navy'] } },
      { title: 'Portable Bluetooth Speaker', type: 'Audio', price: '49.99', compare: '65.00', tags: ['audio', 'speaker', 'bluetooth', 'portable', 'sale'], desc: 'Waterproof speaker with 360° sound and 12-hour battery. Outdoor adventures ready.', img: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&h=800&fit=crop', options: { Color: ['Black', 'Teal', 'Red'] } },
      { title: 'Smart Fitness Tracker', type: 'Gadgets', price: '59.99', compare: '75.00', tags: ['gadgets', 'fitness', 'wearable', 'smartwatch', 'sale'], desc: 'Fitness tracker with heart rate, sleep tracking, GPS, and 7-day battery.', img: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&h=800&fit=crop', options: { Color: ['Black', 'Rose Gold', 'Blue'] } },
      { title: 'Fast Wireless Charger Pad', type: 'Accessories', price: '24.99', compare: '35.00', tags: ['accessories', 'charger', 'wireless', 'sale'], desc: '15W fast wireless charging pad for all Qi devices. Sleek minimalist design.', img: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=800&fit=crop', options: { Color: ['White', 'Black'] } },
      { title: 'USB-C Hub 7-in-1', type: 'Accessories', price: '39.99', compare: '', tags: ['accessories', 'hub', 'usb-c', 'laptop'], desc: 'All-in-one USB-C hub: HDMI, SD card, USB 3.0 ports, and 100W power delivery.', img: 'https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?w=800&h=800&fit=crop', options: { Color: ['Space Grey', 'Silver'] } },
      { title: 'True Wireless Earbuds', type: 'Audio', price: '44.99', compare: '59.99', tags: ['audio', 'earbuds', 'wireless', 'best-sellers', 'sale'], desc: 'Compact TWS earbuds with deep bass, touch controls, and 24-hour battery with case.', img: 'https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=800&h=800&fit=crop', options: { Color: ['White', 'Black', 'Mint'] } },
      { title: 'LED Desk Lamp with Wireless Charging', type: 'Gadgets', price: '54.99', compare: '70.00', tags: ['gadgets', 'lamp', 'desk', 'wireless-charging', 'sale'], desc: 'Adjustable LED desk lamp with built-in wireless charger and 5 brightness levels.', img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop', options: { Color: ['White', 'Black'] } },
      { title: 'Mechanical Keyboard Compact', type: 'Accessories', price: '69.99', compare: '85.00', tags: ['accessories', 'keyboard', 'mechanical', 'gaming', 'sale'], desc: '65% compact mechanical keyboard with hot-swappable switches and RGB backlight.', img: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&h=800&fit=crop', options: { Switch: ['Red (Linear)', 'Blue (Clicky)', 'Brown (Tactile)'] } },
      { title: 'Portable Power Bank 20000mAh', type: 'Accessories', price: '34.99', compare: '', tags: ['accessories', 'power-bank', 'portable', 'best-sellers'], desc: '20000mAh power bank with dual USB-C and USB-A. Charges 3 devices at once.', img: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&h=800&fit=crop', options: { Color: ['Black', 'White'] } },
      { title: 'Smart Home Mini Speaker', type: 'Audio', price: '39.99', compare: '50.00', tags: ['audio', 'smart-home', 'speaker', 'voice-assistant', 'sale'], desc: 'Voice-controlled smart speaker with rich sound and smart home integration.', img: 'https://images.unsplash.com/photo-1543512214-318228f8f096?w=800&h=800&fit=crop', options: { Color: ['Charcoal', 'Sand', 'Blue'] } },
      { title: 'Webcam 4K Auto-Focus', type: 'Gadgets', price: '64.99', compare: '78.00', tags: ['gadgets', 'webcam', '4k', 'streaming', 'new-arrivals', 'sale'], desc: '4K webcam with auto-focus, auto-light correction, and dual noise-cancelling mics.', img: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&h=800&fit=crop', options: { Resolution: ['1080p', '4K'] } },
      { title: 'Wireless Gaming Mouse', type: 'Accessories', price: '49.99', compare: '', tags: ['accessories', 'mouse', 'gaming', 'wireless', 'new-arrivals'], desc: 'Lightweight wireless gaming mouse with 25K DPI sensor and 70-hour battery.', img: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=800&fit=crop', options: { Color: ['Black', 'White'] } },
      { title: 'Laptop Stand Adjustable', type: 'Accessories', price: '29.99', compare: '36.00', tags: ['accessories', 'laptop-stand', 'ergonomic', 'sale'], desc: 'Aluminum adjustable laptop stand. 6 height settings for ergonomic positioning.', img: 'https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?w=800&h=800&fit=crop', options: { Color: ['Silver', 'Space Grey'] } },
      { title: 'Smart Plug 4-Pack', type: 'Smart Home', price: '29.99', compare: '', tags: ['smart-home', 'smart-plug', 'wifi', 'automation', 'best-sellers'], desc: 'WiFi smart plugs with app and voice control. Schedule and automate any device.', img: 'https://images.unsplash.com/photo-1543512214-318228f8f096?w=800&h=800&fit=crop', options: { Pack: ['2-Pack', '4-Pack'] } },
      { title: 'Noise Machine for Sleep', type: 'Gadgets', price: '34.99', compare: '', tags: ['gadgets', 'sleep', 'white-noise', 'wellness'], desc: '30 soothing sounds including white noise, rain, and ocean. Timer and night light.', img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop', options: { Color: ['White', 'Grey'] } },
      { title: 'Ring Light 10-inch', type: 'Accessories', price: '24.99', compare: '30.00', tags: ['accessories', 'ring-light', 'streaming', 'content-creator', 'sale'], desc: '10-inch LED ring light with tripod and phone holder. 3 color modes, 10 brightness levels.', img: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&h=800&fit=crop', options: { Size: ['10 inch', '12 inch'] } },
      { title: 'USB Microphone Condenser', type: 'Audio', price: '59.99', compare: '72.00', tags: ['audio', 'microphone', 'usb', 'podcast', 'new-arrivals', 'sale'], desc: 'Studio-quality USB condenser mic for podcasts, streaming, and meetings.', img: 'https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=800&h=800&fit=crop', options: { Color: ['Black', 'Silver'] } },
      { title: 'Portable SSD 1TB', type: 'Storage', price: '79.99', compare: '95.00', tags: ['storage', 'ssd', 'portable', 'fast', 'sale'], desc: 'Ultra-fast portable SSD with 1050MB/s read speed. Shock-resistant and pocket-sized.', img: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&h=800&fit=crop', options: { Capacity: ['500GB', '1TB', '2TB'] } },
      { title: 'Smart LED Light Strip 5m', type: 'Smart Home', price: '22.99', compare: '', tags: ['smart-home', 'led-strip', 'rgb', 'ambiance', 'new-arrivals'], desc: 'WiFi RGB LED strip with app control and music sync. 16 million colors.', img: 'https://images.unsplash.com/photo-1543512214-318228f8f096?w=800&h=800&fit=crop', options: { Length: ['5m', '10m'] } },
      { title: 'Tablet Stand Multi-Angle', type: 'Accessories', price: '18.99', compare: '24.00', tags: ['accessories', 'tablet-stand', 'adjustable', 'sale'], desc: 'Heavy-duty aluminum tablet stand. Fits 4-13 inch devices. Multi-angle adjustable.', img: 'https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?w=800&h=800&fit=crop', options: { Color: ['Silver', 'Black', 'Rose Gold'] } },
    ]
  },

  jewelry: {
    vendor: 'FlexiLux', tags_base: ['jewelry', 'accessories'],
    products: [
      { title: 'Dainty Gold Chain Necklace', type: 'Necklaces', price: '42.99', compare: '55.00', tags: ['necklaces', 'gold', 'dainty', 'best-sellers', 'sale'], desc: '18K gold-plated chain necklace with minimalist pendant. Hypoallergenic and tarnish-resistant.', img: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop', options: { Length: ['16 inch', '18 inch', '20 inch'] } },
      { title: 'Sterling Silver Stacking Rings Set', type: 'Rings', price: '38.99', compare: '', tags: ['rings', 'silver', 'stacking', 'best-sellers'], desc: 'Set of 3 sterling silver stacking rings with different textures.', img: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=800&fit=crop', options: { Size: ['5', '6', '7', '8'] } },
      { title: 'Pearl Drop Earrings', type: 'Earrings', price: '34.99', compare: '45.00', tags: ['earrings', 'pearl', 'drop', 'sale'], desc: 'Freshwater pearl drop earrings with 18K gold-plated hooks. Timeless elegance.', img: 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&h=800&fit=crop', options: { Type: ['Small Pearl', 'Large Pearl'] } },
      { title: 'Layered Chain Bracelet', type: 'Bracelets', price: '29.99', compare: '', tags: ['bracelets', 'gold', 'layered', 'new-arrivals'], desc: 'Multi-strand gold chain bracelet with adjustable clasp. Instant elegance.', img: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop', options: { Material: ['Gold-Plated', 'Silver'] } },
      { title: 'Cubic Zirconia Stud Earrings', type: 'Earrings', price: '24.99', compare: '32.00', tags: ['earrings', 'studs', 'cz', 'everyday', 'sale'], desc: 'Brilliant CZ stud earrings in classic four-prong setting. Everyday sparkle.', img: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&h=800&fit=crop', options: { Size: ['4mm', '6mm', '8mm'], Metal: ['Silver', 'Gold'] } },
      { title: 'Birthstone Pendant Necklace', type: 'Necklaces', price: '46.99', compare: '58.00', tags: ['necklaces', 'birthstone', 'pendant', 'gift', 'sale'], desc: 'Personalized birthstone pendant on a delicate chain. Perfect meaningful gift.', img: 'https://images.unsplash.com/photo-1515562141589-67f0d569b5a4?w=800&h=800&fit=crop', options: { Month: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] } },
      { title: 'Minimalist Signet Ring', type: 'Rings', price: '36.99', compare: '', tags: ['rings', 'signet', 'minimalist', 'men'], desc: 'Clean-lined signet ring in polished stainless steel. Modern timeless classic.', img: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&h=800&fit=crop', options: { Size: ['6', '7', '8', '9', '10'], Metal: ['Gold', 'Silver', 'Rose Gold'] } },
      { title: 'Hoop Earrings Gold', type: 'Earrings', price: '28.99', compare: '35.00', tags: ['earrings', 'hoops', 'gold', 'sale'], desc: 'Classic gold-plated hoop earrings with click-top closure. Lightweight and comfortable.', img: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&h=800&fit=crop', options: { Size: ['Small 20mm', 'Medium 30mm', 'Large 40mm'] } },
      { title: 'Charm Necklace Collection', type: 'Necklaces', price: '52.99', compare: '68.00', tags: ['necklaces', 'charm', 'collection', 'sale'], desc: 'Interchangeable charm necklace with 3 charms of your choice. Build your story.', img: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&h=800&fit=crop', options: { Chain: ['Gold', 'Silver'] } },
      { title: 'Twisted Band Ring', type: 'Rings', price: '32.99', compare: '', tags: ['rings', 'band', 'twisted', 'sterling-silver'], desc: 'Elegant twisted band ring handcrafted in sterling silver. Beautiful alone or stacked.', img: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&h=800&fit=crop', options: { Size: ['5', '6', '7', '8', '9'], Metal: ['Silver', 'Gold-Plated'] } },
      { title: 'Tennis Bracelet Crystal', type: 'Bracelets', price: '54.99', compare: '68.00', tags: ['bracelets', 'tennis', 'crystal', 'elegant', 'new-arrivals', 'sale'], desc: 'Classic tennis bracelet with round-cut crystals in claw setting. Red carpet glamour.', img: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop', options: { Metal: ['Silver', 'Gold', 'Rose Gold'] } },
      { title: 'Anklet Dainty Chain', type: 'Anklets', price: '19.99', compare: '', tags: ['anklets', 'dainty', 'chain', 'summer', 'new-arrivals'], desc: 'Delicate chain anklet with tiny charm detail. Perfect for summer and beach days.', img: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop', options: { Metal: ['Gold', 'Silver'], Length: ['9 inch', '10 inch'] } },
      { title: 'Men\'s Chain Necklace', type: 'Necklaces', price: '39.99', compare: '', tags: ['necklaces', 'men', 'chain', 'stainless-steel', 'best-sellers'], desc: 'Bold stainless steel chain necklace for men. Tarnish-free, hypoallergenic.', img: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=800&fit=crop', options: { Style: ['Cuban', 'Figaro', 'Rope'], Length: ['20 inch', '22 inch', '24 inch'] } },
      { title: 'Ear Cuff Set No-Piercing', type: 'Earrings', price: '16.99', compare: '20.00', tags: ['earrings', 'ear-cuff', 'no-piercing', 'trendy', 'sale'], desc: 'Set of 5 adjustable ear cuffs. No piercing needed — just slide and wear.', img: 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&h=800&fit=crop', options: { Metal: ['Gold', 'Silver', 'Mixed'] } },
      { title: 'Jewelry Box Organizer', type: 'Storage', price: '34.99', compare: '42.00', tags: ['storage', 'jewelry-box', 'organizer', 'gift', 'sale'], desc: 'Vegan leather jewelry box with mirror, ring rolls, and compartments. Travel-friendly.', img: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&h=800&fit=crop', options: { Color: ['Blush Pink', 'Black', 'White', 'Sage'] } },
      { title: 'Initial Letter Necklace', type: 'Necklaces', price: '28.99', compare: '', tags: ['necklaces', 'initial', 'personalized', 'gift', 'best-sellers'], desc: 'Personalized initial pendant in your letter choice. Dainty and meaningful.', img: 'https://images.unsplash.com/photo-1515562141589-67f0d569b5a4?w=800&h=800&fit=crop', options: { Letter: ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'], Metal: ['Gold', 'Silver', 'Rose Gold'] } },
      { title: 'Cocktail Ring Statement', type: 'Rings', price: '44.99', compare: '55.00', tags: ['rings', 'statement', 'cocktail', 'gemstone', 'sale'], desc: 'Bold statement cocktail ring with oversized faceted crystal. Party-ready glamour.', img: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=800&fit=crop', options: { Stone: ['Emerald', 'Sapphire', 'Ruby', 'Amethyst'], Size: ['6', '7', '8'] } },
      { title: 'Huggie Hoop Earrings', type: 'Earrings', price: '22.99', compare: '', tags: ['earrings', 'huggie', 'hoops', 'everyday', 'new-arrivals'], desc: 'Small huggie hoop earrings that sit close to the earlobe. Sleek and versatile.', img: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&h=800&fit=crop', options: { Metal: ['Gold', 'Silver', 'Rose Gold'] } },
      { title: 'Cuff Bracelet Hammered', type: 'Bracelets', price: '32.99', compare: '40.00', tags: ['bracelets', 'cuff', 'hammered', 'artisan', 'sale'], desc: 'Hand-hammered open cuff bracelet. Adjustable fit, artisan-crafted texture.', img: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=800&fit=crop', options: { Metal: ['Gold', 'Silver'] } },
      { title: 'Jewelry Cleaning Kit', type: 'Care', price: '14.99', compare: '', tags: ['care', 'cleaning', 'maintenance', 'gift'], desc: 'Professional jewelry cleaning solution with dip tray, brush, and polishing cloth.', img: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&h=800&fit=crop', options: { Type: ['Silver Care', 'Gold Care', 'Universal'] } },
    ]
  },

  pets: {
    vendor: 'FlexiPaw', tags_base: ['pets', 'pet-supplies'],
    products: [
      { title: 'Organic Dog Treats Peanut Butter', type: 'Dog Treats', price: '14.99', compare: '18.00', tags: ['dog', 'treats', 'organic', 'peanut-butter', 'best-sellers', 'sale'], desc: 'All-natural organic dog treats with real peanut butter. No fillers, no artificial flavors.', img: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=800&h=800&fit=crop', options: { Size: ['100g', '250g', '500g'] } },
      { title: 'Interactive Cat Feather Toy', type: 'Cat Toys', price: '12.99', compare: '', tags: ['cat', 'toys', 'interactive', 'feather'], desc: 'Retractable feather wand toy. Triggers natural hunting instincts for hours of fun.', img: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=800&h=800&fit=crop', options: { Color: ['Blue', 'Pink', 'Green'] } },
      { title: 'Memory Foam Dog Bed', type: 'Dog Beds', price: '59.99', compare: '75.00', tags: ['dog', 'beds', 'memory-foam', 'orthopedic', 'best-sellers', 'sale'], desc: 'Orthopedic memory foam dog bed with removable washable cover.', img: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&h=800&fit=crop', options: { Size: ['Small', 'Medium', 'Large', 'XL'] } },
      { title: 'Adjustable Dog Harness', type: 'Dog Gear', price: '27.99', compare: '35.00', tags: ['dog', 'harness', 'walking', 'no-pull', 'sale'], desc: 'No-pull adjustable harness with reflective strips and padded chest plate.', img: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800&h=800&fit=crop', options: { Size: ['XS', 'S', 'M', 'L', 'XL'], Color: ['Black', 'Red', 'Blue'] } },
      { title: 'Cat Scratching Post Tower', type: 'Cat Furniture', price: '44.99', compare: '55.00', tags: ['cat', 'scratching', 'furniture', 'tower', 'sale'], desc: 'Multi-level scratching post with sisal rope, perch, and hanging toy.', img: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=800&h=800&fit=crop', options: { Color: ['Beige', 'Grey'] } },
      { title: 'Squeaky Plush Dog Toy Set', type: 'Dog Toys', price: '16.99', compare: '', tags: ['dog', 'toys', 'plush', 'squeaky'], desc: 'Set of 5 squeaky plush toys in fun animal shapes. Soft, durable, entertaining.', img: 'https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=800&h=800&fit=crop', options: { Set: ['Safari Set', 'Farm Set'] } },
      { title: 'Premium Catnip Blend', type: 'Cat Treats', price: '9.99', compare: '12.00', tags: ['cat', 'catnip', 'treats', 'organic', 'sale'], desc: '100% organic premium catnip. Watch your cat roll, rub, and play with pure joy!', img: 'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=800&h=800&fit=crop', options: { Size: ['25g', '50g'] } },
      { title: 'Retractable Dog Leash', type: 'Dog Gear', price: '22.99', compare: '28.00', tags: ['dog', 'leash', 'walking', 'retractable', 'sale'], desc: '16ft retractable leash with one-button lock and comfortable grip handle.', img: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=800&fit=crop', options: { Size: ['Small (up to 25lbs)', 'Large (up to 70lbs)'], Color: ['Black', 'Blue'] } },
      { title: 'Self-Cleaning Cat Litter Mat', type: 'Cat Accessories', price: '19.99', compare: '', tags: ['cat', 'litter', 'mat', 'self-cleaning'], desc: 'Double-layer honeycomb design traps litter from paws. Easy to clean, waterproof.', img: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=800&fit=crop', options: { Size: ['Standard', 'Large'] } },
      { title: 'Indestructible Rubber Chew Toy', type: 'Dog Toys', price: '13.99', compare: '17.00', tags: ['dog', 'toys', 'chew', 'durable', 'sale'], desc: 'Ultra-tough rubber chew toy for aggressive chewers. Bounces, floats, holds treats.', img: 'https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=800&h=800&fit=crop', options: { Size: ['Small', 'Medium', 'Large'] } },
      { title: 'Automatic Pet Water Fountain', type: 'Feeding', price: '34.99', compare: '42.00', tags: ['feeding', 'water-fountain', 'automatic', 'cat', 'dog', 'best-sellers', 'sale'], desc: 'Filtered flowing water fountain. Encourages pets to drink more. Quiet pump.', img: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=800&fit=crop', options: { Capacity: ['1.5L', '2.5L'] } },
      { title: 'Dog Poop Bag Dispenser', type: 'Dog Gear', price: '11.99', compare: '', tags: ['dog', 'poop-bags', 'walking', 'eco'], desc: 'Bone-shaped dispenser with 60 biodegradable bags. Clips to any leash.', img: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=800&fit=crop', options: { Color: ['Black', 'Green', 'Pink'] } },
      { title: 'Cat Window Perch', type: 'Cat Furniture', price: '29.99', compare: '', tags: ['cat', 'furniture', 'window-perch', 'new-arrivals'], desc: 'Sturdy suction-cup window perch for bird watching. Holds up to 30 lbs.', img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=800&fit=crop', options: { Color: ['Grey', 'Brown'] } },
      { title: 'Pet Grooming Brush', type: 'Grooming', price: '15.99', compare: '19.00', tags: ['grooming', 'brush', 'deshedding', 'dog', 'cat', 'sale'], desc: 'Self-cleaning deshedding brush. Removes loose fur with one click release.', img: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800&h=800&fit=crop', options: { Size: ['Small (cats)', 'Large (dogs)'] } },
      { title: 'Elevated Pet Food Bowls', type: 'Feeding', price: '24.99', compare: '30.00', tags: ['feeding', 'bowls', 'elevated', 'dog', 'sale'], desc: 'Bamboo-stand elevated dog bowls with stainless steel inserts. Better for digestion.', img: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=800&h=800&fit=crop', options: { Size: ['Small', 'Medium', 'Large'] } },
      { title: 'Calming Dog Bed Donut', type: 'Dog Beds', price: '39.99', compare: '48.00', tags: ['dog', 'beds', 'calming', 'anxiety', 'new-arrivals', 'sale'], desc: 'Round donut-shaped calming bed with raised edges. Reduces anxiety with cozy nesting.', img: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&h=800&fit=crop', options: { Size: ['Small', 'Medium', 'Large'], Color: ['Grey', 'Beige', 'Pink'] } },
      { title: 'Pet GPS Tracker', type: 'Tech', price: '49.99', compare: '', tags: ['tech', 'gps', 'tracker', 'safety', 'dog', 'cat', 'new-arrivals'], desc: 'Lightweight GPS tracker that attaches to any collar. Real-time location tracking via app.', img: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=800&fit=crop', options: { Color: ['Black', 'Blue', 'Green'] } },
      { title: 'Cat Tunnel Collapsible', type: 'Cat Toys', price: '17.99', compare: '', tags: ['cat', 'toys', 'tunnel', 'play'], desc: '3-way collapsible play tunnel with crinkle material and peek holes. Folds flat.', img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=800&fit=crop', options: { Type: ['2-Way', '3-Way'] } },
      { title: 'Dog Raincoat Waterproof', type: 'Dog Apparel', price: '24.99', compare: '30.00', tags: ['dog', 'apparel', 'raincoat', 'waterproof', 'sale'], desc: 'Lightweight waterproof dog raincoat with reflective strips and belly strap.', img: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=800&fit=crop', options: { Size: ['XS', 'S', 'M', 'L', 'XL'], Color: ['Yellow', 'Red', 'Blue'] } },
      { title: 'Pet First Aid Kit', type: 'Health', price: '21.99', compare: '', tags: ['health', 'first-aid', 'safety', 'dog', 'cat', 'best-sellers'], desc: '40-piece pet first aid kit: bandages, antiseptic, tick remover, emergency guide.', img: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800&h=800&fit=crop', options: { Type: ['Standard', 'Travel Size'] } },
    ]
  },

  general: {
    vendor: 'FlexiStore', tags_base: ['trending', 'popular'],
    products: [
      { title: 'Premium Cotton T-Shirt', type: 'Clothing', price: '24.99', compare: '32.00', tags: ['new-arrivals', 'clothing', 'cotton', 'sale'], desc: 'Ultra-soft premium cotton t-shirt. Classic fit in multiple colors.', img: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop', options: { Color: ['White', 'Black', 'Navy', 'Grey'], Size: ['S', 'M', 'L', 'XL'] } },
      { title: 'Stainless Steel Water Bottle', type: 'Accessories', price: '19.99', compare: '', tags: ['best-sellers', 'accessories', 'eco', 'drinkware'], desc: 'Double-wall insulated bottle. Cold 24hrs, hot 12hrs.', img: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop', options: { Color: ['Silver', 'Matte Black', 'Rose Gold'], Size: ['500ml', '750ml'] } },
      { title: 'Wireless Charging Pad', type: 'Electronics', price: '29.99', compare: '39.99', tags: ['new-arrivals', 'electronics', 'wireless', 'sale'], desc: 'Sleek 15W fast wireless charging pad for all Qi devices.', img: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=800&fit=crop', options: { Color: ['White', 'Black'] } },
      { title: 'Scented Soy Candle Set', type: 'Home', price: '34.99', compare: '42.00', tags: ['best-sellers', 'home', 'candles', 'gift', 'sale'], desc: 'Set of 3 hand-poured soy candles in calming scents. 45+ hour burn each.', img: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=800&h=800&fit=crop', options: { Scent: ['Lavender', 'Citrus', 'Woody'] } },
      { title: 'Leather Bifold Wallet', type: 'Accessories', price: '39.99', compare: '50.00', tags: ['sale', 'accessories', 'leather', 'men'], desc: 'Genuine leather RFID-blocking bifold wallet. Slim profile, 8 card slots.', img: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&h=800&fit=crop', options: { Color: ['Brown', 'Black', 'Tan'] } },
      { title: 'Yoga Mat Premium', type: 'Fitness', price: '44.99', compare: '', tags: ['best-sellers', 'fitness', 'yoga'], desc: 'Non-slip premium yoga mat with alignment lines. 6mm for joint protection.', img: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=800&fit=crop', options: { Color: ['Purple', 'Teal', 'Black', 'Pink'] } },
      { title: 'Bamboo Sunglasses', type: 'Accessories', price: '27.99', compare: '35.00', tags: ['new-arrivals', 'accessories', 'eco', 'sunglasses', 'sale'], desc: 'Polarized bamboo frame sunglasses with UV400 protection.', img: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&h=800&fit=crop', options: { Lens: ['Brown', 'Green', 'Blue Mirror'] } },
      { title: 'Organic Tea Collection', type: 'Food', price: '22.99', compare: '', tags: ['best-sellers', 'food', 'organic', 'tea'], desc: 'Curated box of 6 organic loose-leaf teas from around the world.', img: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=800&h=800&fit=crop', options: { Type: ['Classic', 'Herbal'] } },
      { title: 'Minimalist Desk Organizer', type: 'Home', price: '32.99', compare: '40.00', tags: ['sale', 'home', 'office', 'organizer'], desc: 'Sleek wooden desk organizer for pens, phone, and supplies.', img: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop', options: { Material: ['Walnut', 'Oak', 'Bamboo'] } },
      { title: 'Bluetooth Portable Speaker', type: 'Electronics', price: '49.99', compare: '65.00', tags: ['sale', 'electronics', 'audio', 'bluetooth'], desc: 'Waterproof portable Bluetooth speaker with 12-hour battery and deep bass.', img: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&h=800&fit=crop', options: { Color: ['Black', 'Blue', 'Red'] } },
      { title: 'Linen Throw Blanket', type: 'Home', price: '44.99', compare: '55.00', tags: ['home', 'blanket', 'linen', 'cozy', 'sale'], desc: 'Stonewashed linen throw blanket with fringe edges. Gets softer with every wash.', img: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=800&h=800&fit=crop', options: { Color: ['Natural', 'Grey', 'Sage', 'Dusty Rose'] } },
      { title: 'Leather Journal Notebook', type: 'Stationery', price: '24.99', compare: '', tags: ['stationery', 'journal', 'leather', 'gift', 'new-arrivals'], desc: 'Handmade leather journal with thick cotton paper. 200 pages of writing space.', img: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&h=800&fit=crop', options: { Color: ['Brown', 'Black', 'Tan'] } },
      { title: 'Ceramic Planter Set', type: 'Home', price: '29.99', compare: '36.00', tags: ['home', 'planters', 'ceramic', 'boho', 'sale'], desc: 'Set of 3 ceramic planters with drainage holes and bamboo saucers.', img: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=800&h=800&fit=crop', options: { Color: ['White', 'Terracotta', 'Sage'] } },
      { title: 'Resistance Bands Set', type: 'Fitness', price: '18.99', compare: '24.00', tags: ['fitness', 'resistance-bands', 'workout', 'sale'], desc: '5 resistance levels for full body workouts. Door anchor and handles included.', img: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=800&fit=crop', options: { Set: ['Standard', 'Heavy'] } },
      { title: 'Essential Oil Diffuser', type: 'Wellness', price: '34.99', compare: '', tags: ['wellness', 'diffuser', 'aromatherapy', 'best-sellers'], desc: 'Ultrasonic essential oil diffuser with 7 LED colors and auto shutoff. Whisper quiet.', img: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=800&h=800&fit=crop', options: { Color: ['White', 'Wood Grain', 'Black'] } },
      { title: 'Cotton Tote Bag', type: 'Accessories', price: '14.99', compare: '', tags: ['accessories', 'tote', 'eco', 'cotton'], desc: 'Heavy-duty organic cotton tote with reinforced handles. Reusable and stylish.', img: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop', options: { Design: ['Plain', 'Minimal Print', 'Bold Print'] } },
      { title: 'Cozy Knit Socks 3-Pack', type: 'Clothing', price: '16.99', compare: '20.00', tags: ['clothing', 'socks', 'cozy', 'winter', 'sale'], desc: 'Super-soft merino wool blend socks. Warm, breathable, and perfect for lounging.', img: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop', options: { Pattern: ['Solid', 'Striped', 'Fair Isle'], Size: ['S/M', 'L/XL'] } },
      { title: 'Phone Case Clear Slim', type: 'Electronics', price: '12.99', compare: '', tags: ['electronics', 'phone-case', 'clear', 'slim'], desc: 'Crystal-clear slim phone case with shock-absorbing corners. Shows off your phone.', img: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=800&fit=crop', options: { Model: ['iPhone 15', 'iPhone 15 Pro', 'iPhone 14', 'Samsung S24', 'Samsung S23'] } },
      { title: 'Stainless Steel Straw Set', type: 'Eco', price: '9.99', compare: '', tags: ['eco', 'straws', 'reusable', 'stainless-steel'], desc: 'Set of 4 reusable straws with cleaning brush and cotton pouch. Ditch the plastic.', img: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop', options: { Type: ['Straight', 'Bent', 'Mixed'] } },
      { title: 'Puzzle 1000 Pieces', type: 'Games', price: '19.99', compare: '24.00', tags: ['games', 'puzzle', 'family', 'gift', 'sale'], desc: 'Beautiful 1000-piece jigsaw puzzle. Thick pieces, minimal dust, poster included.', img: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=800&h=800&fit=crop', options: { Design: ['Mountain Sunset', 'City Skyline', 'Ocean Waves', 'Forest Path'] } },
    ]
  },
};

// ---- CSV Generation Engine ----
const headers = [
  'Handle','Title','Body (HTML)','Vendor','Product Category','Type','Tags',
  'Published','Option1 Name','Option1 Value','Option2 Name','Option2 Value',
  'Option3 Name','Option3 Value','Variant SKU','Variant Grams','Variant Inventory Tracker',
  'Variant Inventory Policy','Variant Fulfillment Service','Variant Price',
  'Variant Compare At Price','Variant Requires Shipping','Variant Taxable',
  'Image Src','Image Position','Image Alt Text','Gift Card','SEO Title',
  'SEO Description','Status'
];

function esc(v) {
  if (v == null) return '';
  const s = String(v);
  return (s.includes(',') || s.includes('"') || s.includes('\n')) ? '"' + s.replace(/"/g, '""') + '"' : s;
}
function handle(t) { return t.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, ''); }
function sku(h, i) { return h.substring(0, 8).toUpperCase().replace(/-/g, '') + '-' + String(i).padStart(3, '0'); }
function combos(arrays, cur = []) {
  if (cur.length === arrays.length) return [cur];
  const r = [];
  for (const v of arrays[cur.length]) r.push(...combos(arrays, [...cur, v]));
  return r;
}

const niche = process.argv[2];

if (!niche || !niches[niche]) {
  console.log('\nAvailable niches:', Object.keys(niches).join(', '));
  console.log('Usage: node generate-all-csv.js <niche>');
  console.log('   or: node generate-all-csv.js all\n');
  if (niche !== 'all') process.exit(0);
}

const targets = niche === 'all' ? Object.keys(niches) : [niche];

targets.forEach(n => {
  const data = niches[n];
  const rows = [headers.map(esc).join(',')];

  data.products.forEach(p => {
    const h = handle(p.title);
    const tags = [...data.tags_base, ...p.tags].join(', ');
    const oNames = Object.keys(p.options);
    const oVals = Object.values(p.options);
    const cs = combos(oVals);

    cs.forEach((c, vi) => {
      const first = vi === 0;
      rows.push([
        h, first ? p.title : '', first ? '<p>'+p.desc+'</p>' : '', first ? data.vendor : '',
        '', first ? p.type : '', first ? tags : '', 'true',
        oNames[0]||'', c[0]||'', oNames[1]||'', c[1]||'', oNames[2]||'', c[2]||'',
        sku(h, vi+1), '200', 'shopify', 'deny', 'manual',
        p.price, p.compare||'', 'true', 'true',
        first ? (p.img||'') : '', first ? '1' : '', first ? p.title : '',
        'false', first ? p.title : '', first ? p.desc.substring(0,160) : '', 'active'
      ].map(esc).join(','));
    });
  });

  const file = `shopify-products-${n}.csv`;
  fs.writeFileSync(file, rows.join('\n'), 'utf8');
  console.log(`  ${n}: ${data.products.length} products, ${rows.length-1} variants -> ${file}`);
});

console.log('\nDone! Import via Shopify Admin > Products > Import');
